-- MySQL Script generated by MySQL Workbench
-- Wed Jun  9 18:51:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema swiss_culture_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `swiss_culture_db` ;

-- -----------------------------------------------------
-- Schema swiss_culture_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `swiss_culture_db` DEFAULT CHARACTER SET utf8 ;
USE `swiss_culture_db` ;

-- -----------------------------------------------------
-- Table `swiss_culture_db`.`compte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`compte` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`compte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `motDePasse` VARCHAR(255) NULL,
  `email` VARCHAR(254) NULL,
  `nomProfil` VARCHAR(50) NULL,
  `noTelephone` VARCHAR(50) NULL,
  `estActif` TINYINT(1) NULL,
  `idFacebook` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `nomProfil_UNIQUE` (`nomProfil` ASC),
  UNIQUE INDEX `idFacebook_UNIQUE` (`idFacebook` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiss_culture_db`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`categorie` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiss_culture_db`.`canton`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`canton` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`canton` (
  `sigle` VARCHAR(20) NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`sigle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiss_culture_db`.`ville`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`ville` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`ville` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `NPA` INT NULL,
  `canton_sigle` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ville_Canton1_idx` (`canton_sigle` ASC),
  CONSTRAINT `fk_Ville_Canton1`
    FOREIGN KEY (`canton_sigle`)
    REFERENCES `swiss_culture_db`.`canton` (`sigle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiss_culture_db`.`domaine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`domaine` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`domaine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiss_culture_db`.`institution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`institution` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`institution` (
  `id` INT NOT NULL,
  `description` VARCHAR(1000) NULL,
  `siteWeb` VARCHAR(250) NULL,
  `typeWatermark` SMALLINT(100) NULL,
  `imageProfil` VARCHAR(255) NULL,
  `filigrane` VARCHAR(255) NULL,
  `estValide` TINYINT(1) NULL,
  `ville_id` INT NULL,
  `domaine_id` INT NULL,
  `rue` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Institution_Ville1_idx` (`ville_id` ASC),
  INDEX `fk_Institution_Domaine1_idx` (`domaine_id` ASC),
  INDEX `fk_Institution_Compte1_idx` (`id` ASC),
  CONSTRAINT `fk_Institution_Ville1`
    FOREIGN KEY (`ville_id`)
    REFERENCES `swiss_culture_db`.`ville` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Institution_Domaine1`
    FOREIGN KEY (`domaine_id`)
    REFERENCES `swiss_culture_db`.`domaine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Institution_Compte1`
    FOREIGN KEY (`id`)
    REFERENCES `swiss_culture_db`.`compte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiss_culture_db`.`visite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`visite` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`visite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `estVisible` TINYINT(1) NULL,
  `institution_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_visite_institution1_idx` (`institution_id` ASC),
  CONSTRAINT `fk_visite_institution1`
    FOREIGN KEY (`institution_id`)
    REFERENCES `swiss_culture_db`.`institution` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiss_culture_db`.`prive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`prive` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`prive` (
  `id` INT NOT NULL,
  `dateDerniereConnexion` DATE NULL,
  INDEX `fk_Prive_Compte1_idx` (`id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Prive_Compte1`
    FOREIGN KEY (`id`)
    REFERENCES `swiss_culture_db`.`compte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiss_culture_db`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`media` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`media` (
  `idMedia` INT NOT NULL AUTO_INCREMENT,
  `nomFichier` VARCHAR(255) NOT NULL,
  `titre` VARCHAR(100) NULL,
  `auteur` VARCHAR(500) NULL,
  `description` VARCHAR(1000) NULL,
  `date` DATETIME NULL,
  `institution_id` INT NOT NULL,
  PRIMARY KEY (`idMedia`),
  UNIQUE INDEX `nomFichier_UNIQUE` (`nomFichier` ASC),
  INDEX `fk_media_institution1_idx` (`institution_id` ASC),
  CONSTRAINT `fk_media_institution1`
    FOREIGN KEY (`institution_id`)
    REFERENCES `swiss_culture_db`.`institution` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiss_culture_db`.`visite_categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`visite_categorie` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`visite_categorie` (
  `visite_id` INT NOT NULL,
  `categorie_id` INT NOT NULL,
  PRIMARY KEY (`visite_id`, `categorie_id`),
  INDEX `fk_Visite_has_Categorie_Categorie1_idx` (`categorie_id` ASC),
  INDEX `fk_Visite_has_Categorie_Visite1_idx` (`visite_id` ASC),
  CONSTRAINT `fk_Visite_has_Categorie_Visite1`
    FOREIGN KEY (`visite_id`)
    REFERENCES `swiss_culture_db`.`visite` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visite_has_Categorie_Categorie1`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `swiss_culture_db`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiss_culture_db`.`visite_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`visite_media` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`visite_media` (
  `visite_id` INT NOT NULL,
  `media_idMedia` INT NOT NULL,
  `ordre` INT NULL,
  PRIMARY KEY (`visite_id`, `media_idMedia`),
  INDEX `fk_Visite_has_Media_Media1_idx` (`media_idMedia` ASC),
  INDEX `fk_Visite_has_Media_Visite1_idx` (`visite_id` ASC),
  CONSTRAINT `fk_Visite_has_Media_Visite1`
    FOREIGN KEY (`visite_id`)
    REFERENCES `swiss_culture_db`.`visite` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visite_has_Media_Media1`
    FOREIGN KEY (`media_idMedia`)
    REFERENCES `swiss_culture_db`.`media` (`idMedia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiss_culture_db`.`institution_compte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`institution_compte` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`institution_compte` (
  `compte_id` INT NOT NULL,
  `institution_id` INT NOT NULL,
  PRIMARY KEY (`compte_id`, `institution_id`),
  INDEX `fk_compte_has_institution_institution1_idx` (`institution_id` ASC),
  INDEX `fk_compte_has_institution_compte1_idx` (`compte_id` ASC),
  CONSTRAINT `fk_compte_has_institution_compte1`
    FOREIGN KEY (`compte_id`)
    REFERENCES `swiss_culture_db`.`compte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compte_has_institution_institution1`
    FOREIGN KEY (`institution_id`)
    REFERENCES `swiss_culture_db`.`institution` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiss_culture_db`.`prive_favori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`prive_favori` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`prive_favori` (
  `prive_id` INT NOT NULL,
  `institution_id` INT NOT NULL,
  PRIMARY KEY (`prive_id`, `institution_id`),
  INDEX `fk_prive_has_institution_institution1_idx` (`institution_id` ASC),
  INDEX `fk_prive_has_institution_prive1_idx` (`prive_id` ASC),
  CONSTRAINT `fk_prive_has_institution_prive1`
    FOREIGN KEY (`prive_id`)
    REFERENCES `swiss_culture_db`.`prive` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prive_has_institution_institution1`
    FOREIGN KEY (`institution_id`)
    REFERENCES `swiss_culture_db`.`institution` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiss_culture_db`.`like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`like` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`like` (
  `prive_id` INT NOT NULL,
  `visite_id` INT NOT NULL,
  PRIMARY KEY (`prive_id`, `visite_id`),
  INDEX `fk_prive_has_visite_visite1_idx` (`visite_id` ASC),
  INDEX `fk_prive_has_visite_prive1_idx` (`prive_id` ASC),
  CONSTRAINT `fk_prive_has_visite_prive1`
    FOREIGN KEY (`prive_id`)
    REFERENCES `swiss_culture_db`.`prive` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prive_has_visite_visite1`
    FOREIGN KEY (`visite_id`)
    REFERENCES `swiss_culture_db`.`visite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swiss_culture_db`.`prive_categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swiss_culture_db`.`prive_categorie` ;

CREATE TABLE IF NOT EXISTS `swiss_culture_db`.`prive_categorie` (
  `prive_id` INT NOT NULL,
  `categorie_id` INT NOT NULL,
  PRIMARY KEY (`prive_id`, `categorie_id`),
  INDEX `fk_prive_has_categorie_categorie1_idx` (`categorie_id` ASC),
  INDEX `fk_prive_has_categorie_prive1_idx` (`prive_id` ASC),
  CONSTRAINT `fk_prive_has_categorie_prive1`
    FOREIGN KEY (`prive_id`)
    REFERENCES `swiss_culture_db`.`prive` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prive_has_categorie_categorie1`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `swiss_culture_db`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
